---
- name: Configure sshd
  lineinfile:
    dest: "{{ sshd_config_path }}"
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backrefs: yes
  notify: Restart sshd
  with_items:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
